name: Website Scans

on:
  workflow_dispatch: {}
  schedule:
  - cron: '00 10 * * *'

jobs:
  target-list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: >-
          echo 'matrix=[
          "https://ginandjuice.shop/"
          ]' >> $GITHUB_OUTPUT
  dastardly-scan:
    needs: target-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sites: ${{ fromJson(needs.target-list.outputs.matrix) }}
    steps:
    - name: Dastardly Scan
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: ${{ matrix.sites }}
    - name: Process Report
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        check_name: scan results (${{ matrix.sites }})
        report_paths: '**/dastardly-report.xml'
        require_tests: true
        detailed_summary: true
